ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: "style(pre-commit.ci): auto fixes [...]"
  autoupdate_commit_msg: "ci(pre-commit.ci): autoupdate"

repos:
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject
        files: (^|/)pyproject\.toml$

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff-check
      - id: ruff-format
